# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  tests: './PlisskenLibrary.Tests/PlisskenLibrary.Tests.csproj'

steps:
- script: dotnet restore
  displayName: dotnet restore
- script: dotnet clean
  displayName: dotnet clean
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test $(tests) --logger "xunit;LogFileName=TestResults.xml"
  displayName: 'dotnet test'
- task: PublishTestResults@2
  displayName: 'Public test results to Azure Pipelines'
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TestResults.xml'
